server:
  port: 8011
  servlet:
    context-path: /

spring:
  application:
    name: serviceConsumer

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    instance:
      hostname: localhost
    service-url:
      defaultZone: http://localhost:8762/eureka/

##配置feign使用httpclient的客户端提高性能
feign:
  httpclient:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


hystrix:
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 6000  #熔断后多少秒后尝试重新请求
        errorThresholdPercentage: 50  #触发熔断的最小比例
        requestVolumeThreshold: 8  #触发熔断的最小请求次数
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000  #接口超时时间

