server:
  port: 8011
  servlet:
    context-path: /

spring:
  application:
    name: serviceConsumer

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    instance:
      hostname: localhost
    service-url:
      defaultZone: http://localhost:8762/eureka/


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic